package ExceptionsExample;

public class RunTimeException {
	public static void main(String[] args) {
		String[]str= {"one","two", "three"};
		try {
		System.out.println(str[3]);
		}catch (Exception q) {
			System.out.println(q.getClass());
		}
		System.out.println("code is done");
		
		
	}

}
